- FullName: Scan Count
  UnitID: -1
  CalcID: 72
- FullName: Pump Status
  UnitID: -1
  CalcID: 69
- FullName: Descent Rate [m/s]
  UnitID: 32
  CalcID: 18
  extra:
    WindowSize:
      value: 2.0
- FullName: Latitude [deg]
  CalcID: 39
  UnitID: 4
- FullName: Longitude [deg]
  CalcID: 40
  UnitID: 4
- FullName: Time, Elapsed [seconds]
  CalcID: 84
  UnitID: 52